language: c
before_install:
  - if [ ! -d ./android-ndk-r10e ];then wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin ; sudo chmod a+x android-ndk-r10e-linux-x86_64.bin ; ./android-ndk-r10e-linux-x86_64.bin > /dev/null ; fi
  - ./android-configure ./android-ndk-r10e
script:
  - make
  - rm node
  - cp -a out/Release/node node
  - tar czvf android.gz node
deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  file: android.gz
  skip_cleanup: true
  on:
    tags: true
